server:
  port: 0

spring:
#  profiles:
#    active: dev
  application:
    name: user-service
  zipkin:
    base-rul: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bootstrap:
      enabled: true
#  cloud:
#    config:
#      name: ecommerce
#  config:
#    import: optional:configserver:http://127.0.0.1:8888
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commere.

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

#token:
#  expiration_time: 86400000
#  secret: user_tokenuser_tokenuser_tokenuser_tokenuser_tokenuser_tokenuser_token