server:
  port: 0

spring:
  application:
    name: order-service
  zipkin:
    base-rul: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  datasource:
#    url: jdbc:h2:mem:mydb
#    driver-class-name: org.h2.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 428653a
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.orderservice: DEBUG

management:
  endpoint:
    web:
      include: "*"